namespace Lopatnov.Translate.Core.LanguageDetectors;

/// <summary>
/// Converts language codes between formats: BCP-47, FLORES-200, and "native" (passthrough).
/// Default format (empty string) is BCP-47. Unknown codes are passed through as-is.
/// </summary>
public static class LanguageCodeConverter
{
    private static readonly string DefaultFloreCode = "eng_Latn";

    /// <summary>
    /// Converts <paramref name="code"/> from <paramref name="fromFormat"/> to <paramref name="toFormat"/>.
    /// Supported format strings: "bcp47" (default when empty), "flores200", "native".
    /// Unknown codes are returned unchanged.
    /// </summary>
    /// <inheritdoc cref="Convert(string,LanguageCodeFormat,LanguageCodeFormat)"/>
    /// Empty/null format string defaults to BCP-47 (suitable for user-facing APIs).
    public static string Convert(string code, string fromFormat, string toFormat) =>
        Convert(code, ParseFormat(fromFormat), ParseFormat(toFormat));

    // Lenient parsing for string-based API: handles hyphen variants, empty → BCP-47, unknown → Native.
    // Distinct from ToLanguageCodeFormat() which throws on unknown values.
    private static LanguageCodeFormat ParseFormat(string? format) =>
        format?.ToLowerInvariant() switch
        {
            null or "" or "bcp47" or "bcp-47" => LanguageCodeFormat.Bcp47,
            "flores200" or "flores-200"        => LanguageCodeFormat.Flores200,
            "native"                           => LanguageCodeFormat.Native,
            "n/a" or "none"                    => LanguageCodeFormat.None,
            "iso639-1" or "iso639_1"           => LanguageCodeFormat.ISO639_1,
            "iso639-2" or "iso639_2"           => LanguageCodeFormat.ISO639_2,
            "iso639-3" or "iso639_3"           => LanguageCodeFormat.ISO639_3,
            _                                  => LanguageCodeFormat.Native,
        };

    public static string Convert(string code, LanguageCodeFormat fromFormat, LanguageCodeFormat toFormat)
    {
        if (string.IsNullOrEmpty(code) || fromFormat == toFormat || toFormat == LanguageCodeFormat.Native || toFormat == LanguageCodeFormat.None) return code;

        // None format → normalise to the default English FLORES-200 before converting
        string flores = fromFormat switch
        {
            LanguageCodeFormat.None      => DefaultFloreCode,
            LanguageCodeFormat.Flores200 => code,
            LanguageCodeFormat.ISO639_1 or
            LanguageCodeFormat.ISO639_2 or
            LanguageCodeFormat.ISO639_3  => _isoToFlores200.GetValueOrDefault(code, code),
            LanguageCodeFormat.Bcp47     => _bcp47ToFlores200.GetValueOrDefault(code, code), // passthrough for unknown
            _                            => code,
        };

        return toFormat switch
        {
            LanguageCodeFormat.Flores200 => flores,
            LanguageCodeFormat.Bcp47     => _flores200ToBcp47.GetValueOrDefault(flores, flores), // passthrough for unknown
            LanguageCodeFormat.ISO639_1  => _flores200ToIso639_1.Value.GetValueOrDefault(flores, flores),
            LanguageCodeFormat.ISO639_2 or
            LanguageCodeFormat.ISO639_3  => _flores200ToIso639_3.Value.GetValueOrDefault(flores, flores),
            _                            => code,
        };
    }

    // -------------------------------------------------------------------------

    private static readonly Dictionary<string, string> _flores200ToBcp47 =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["eng_Latn"] = "en",
            ["deu_Latn"] = "de",
            ["fra_Latn"] = "fr",
            ["spa_Latn"] = "es",
            ["ita_Latn"] = "it",
            ["por_Latn"] = "pt",
            ["nld_Latn"] = "nl",
            ["pol_Latn"] = "pl",
            ["ces_Latn"] = "cs",
            ["slk_Latn"] = "sk",
            ["slv_Latn"] = "sl",
            ["hun_Latn"] = "hu",
            ["ron_Latn"] = "ro",
            ["bul_Cyrl"] = "bg",
            ["hrv_Latn"] = "hr",
            ["srp_Cyrl"] = "sr",
            ["rus_Cyrl"] = "ru",
            ["ukr_Cyrl"] = "uk",
            ["bel_Cyrl"] = "be",
            ["mkd_Cyrl"] = "mk",
            ["bos_Latn"] = "bs",
            ["lit_Latn"] = "lt",
            ["lvs_Latn"] = "lv",
            ["est_Latn"] = "et",
            ["fin_Latn"] = "fi",
            ["swe_Latn"] = "sv",
            ["nob_Latn"] = "nb",
            ["nno_Latn"] = "nn",
            ["dan_Latn"] = "da",
            ["tur_Latn"] = "tr",
            ["azj_Latn"] = "az",
            ["kaz_Cyrl"] = "kk",
            ["kir_Cyrl"] = "ky",
            ["uzn_Latn"] = "uz",
            ["tgk_Cyrl"] = "tg",
            ["arb_Arab"] = "ar",
            ["pes_Arab"] = "fa",
            ["urd_Arab"] = "ur",
            ["hin_Deva"] = "hi",
            ["ben_Beng"] = "bn",
            ["mar_Deva"] = "mr",
            ["tam_Taml"] = "ta",
            ["tel_Telu"] = "te",
            ["mal_Mlym"] = "ml",
            ["kan_Knda"] = "kn",
            ["guj_Gujr"] = "gu",
            ["pan_Guru"] = "pa",
            ["npi_Deva"] = "ne",
            ["sin_Sinh"] = "si",
            ["zho_Hans"] = "zh-Hans",
            ["cmn_Hani"] = "zh-Hans",
            ["yue_Hant"] = "yue",
            ["jpn_Jpan"] = "ja",
            ["kor_Hang"] = "ko",
            ["vie_Latn"] = "vi",
            ["tha_Thai"] = "th",
            ["khm_Khmr"] = "km",
            ["lao_Laoo"] = "lo",
            ["mya_Mymr"] = "my",
            ["kat_Geor"] = "ka",
            ["hye_Armn"] = "hy",
            ["heb_Hebr"] = "he",
            ["ind_Latn"] = "id",
            ["zsm_Latn"] = "ms",
            ["tgl_Latn"] = "tl",
            ["swh_Latn"] = "sw",
            ["cym_Latn"] = "cy",
            ["eus_Latn"] = "eu",
            ["glg_Latn"] = "gl",
            ["cat_Latn"] = "ca",
            ["afr_Latn"] = "af",
            ["isl_Latn"] = "is",
            ["mlt_Latn"] = "mt",
            ["als_Latn"] = "sq",
            ["khk_Cyrl"] = "mn",
            ["jav_Latn"] = "jv",
            ["sun_Latn"] = "su",
            ["plt_Latn"] = "mg",
            ["epo_Latn"] = "eo",
            ["ell_Grek"] = "el",
        };

    private static readonly Dictionary<string, string> _bcp47ToFlores200 =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = "eng_Latn",
            ["de"] = "deu_Latn",
            ["fr"] = "fra_Latn",
            ["es"] = "spa_Latn",
            ["it"] = "ita_Latn",
            ["pt"] = "por_Latn",
            ["nl"] = "nld_Latn",
            ["pl"] = "pol_Latn",
            ["cs"] = "ces_Latn",
            ["sk"] = "slk_Latn",
            ["sl"] = "slv_Latn",
            ["hu"] = "hun_Latn",
            ["ro"] = "ron_Latn",
            ["bg"] = "bul_Cyrl",
            ["hr"] = "hrv_Latn",
            ["sr"] = "srp_Cyrl",
            ["ru"] = "rus_Cyrl",
            ["uk"] = "ukr_Cyrl",
            ["be"] = "bel_Cyrl",
            ["mk"] = "mkd_Cyrl",
            ["bs"] = "bos_Latn",
            ["lt"] = "lit_Latn",
            ["lv"] = "lvs_Latn",
            ["et"] = "est_Latn",
            ["fi"] = "fin_Latn",
            ["sv"] = "swe_Latn",
            ["nb"] = "nob_Latn",
            ["nn"] = "nno_Latn",
            ["da"] = "dan_Latn",
            ["tr"] = "tur_Latn",
            ["az"] = "azj_Latn",
            ["kk"] = "kaz_Cyrl",
            ["ky"] = "kir_Cyrl",
            ["uz"] = "uzn_Latn",
            ["tg"] = "tgk_Cyrl",
            ["ar"] = "arb_Arab",
            ["fa"] = "pes_Arab",
            ["ur"] = "urd_Arab",
            ["hi"] = "hin_Deva",
            ["bn"] = "ben_Beng",
            ["mr"] = "mar_Deva",
            ["ta"] = "tam_Taml",
            ["te"] = "tel_Telu",
            ["ml"] = "mal_Mlym",
            ["kn"] = "kan_Knda",
            ["gu"] = "guj_Gujr",
            ["pa"] = "pan_Guru",
            ["ne"] = "npi_Deva",
            ["si"] = "sin_Sinh",
            ["zh"] = "zho_Hans",
            ["zh-Hans"] = "zho_Hans",
            ["zh-CN"] = "zho_Hans",
            ["zh-Hant"] = "zho_Hans",
            ["zh-TW"] = "zho_Hans",
            ["yue"] = "yue_Hant",
            ["ja"] = "jpn_Jpan",
            ["ko"] = "kor_Hang",
            ["vi"] = "vie_Latn",
            ["th"] = "tha_Thai",
            ["km"] = "khm_Khmr",
            ["lo"] = "lao_Laoo",
            ["my"] = "mya_Mymr",
            ["ka"] = "kat_Geor",
            ["hy"] = "hye_Armn",
            ["he"] = "heb_Hebr",
            ["id"] = "ind_Latn",
            ["ms"] = "zsm_Latn",
            ["tl"] = "tgl_Latn",
            ["sw"] = "swh_Latn",
            ["cy"] = "cym_Latn",
            ["eu"] = "eus_Latn",
            ["gl"] = "glg_Latn",
            ["ca"] = "cat_Latn",
            ["af"] = "afr_Latn",
            ["is"] = "isl_Latn",
            ["mt"] = "mlt_Latn",
            ["sq"] = "als_Latn",
            ["mn"] = "khk_Cyrl",
            ["jv"] = "jav_Latn",
            ["su"] = "sun_Latn",
            ["mg"] = "plt_Latn",
            ["eo"] = "epo_Latn",
            ["el"] = "ell_Grek",
        };

    // Maps ISO 639-1 and ISO 639-3 labels (as produced by fastText models) to FLORES-200.
    private static readonly Dictionary<string, string> _isoToFlores200 =
        new(StringComparer.OrdinalIgnoreCase)
        {
            // --- ISO 639-1 (fastText LID-176) ---
            ["en"] = "eng_Latn",
            ["de"] = "deu_Latn",
            ["fr"] = "fra_Latn",
            ["es"] = "spa_Latn",
            ["it"] = "ita_Latn",
            ["pt"] = "por_Latn",
            ["nl"] = "nld_Latn",
            ["pl"] = "pol_Latn",
            ["cs"] = "ces_Latn",
            ["sk"] = "slk_Latn",
            ["sl"] = "slv_Latn",
            ["hu"] = "hun_Latn",
            ["ro"] = "ron_Latn",
            ["bg"] = "bul_Cyrl",
            ["hr"] = "hrv_Latn",
            ["sr"] = "srp_Cyrl",
            ["ru"] = "rus_Cyrl",
            ["uk"] = "ukr_Cyrl",
            ["be"] = "bel_Cyrl",
            ["mk"] = "mkd_Cyrl",
            ["bs"] = "bos_Latn",
            ["lt"] = "lit_Latn",
            ["lv"] = "lvs_Latn",
            ["et"] = "est_Latn",
            ["fi"] = "fin_Latn",
            ["sv"] = "swe_Latn",
            ["no"] = "nob_Latn",
            ["da"] = "dan_Latn",
            ["tr"] = "tur_Latn",
            ["az"] = "azj_Latn",
            ["kk"] = "kaz_Cyrl",
            ["ky"] = "kir_Cyrl",
            ["uz"] = "uzn_Latn",
            ["tg"] = "tgk_Cyrl",
            ["ar"] = "arb_Arab",
            ["fa"] = "pes_Arab",
            ["ur"] = "urd_Arab",
            ["hi"] = "hin_Deva",
            ["bn"] = "ben_Beng",
            ["mr"] = "mar_Deva",
            ["ta"] = "tam_Taml",
            ["te"] = "tel_Telu",
            ["ml"] = "mal_Mlym",
            ["kn"] = "kan_Knda",
            ["gu"] = "guj_Gujr",
            ["pa"] = "pan_Guru",
            ["ne"] = "npi_Deva",
            ["si"] = "sin_Sinh",
            ["zh"] = "zho_Hans",
            ["ja"] = "jpn_Jpan",
            ["ko"] = "kor_Hang",
            ["vi"] = "vie_Latn",
            ["th"] = "tha_Thai",
            ["km"] = "khm_Khmr",
            ["lo"] = "lao_Laoo",
            ["my"] = "mya_Mymr",
            ["ka"] = "kat_Geor",
            ["hy"] = "hye_Armn",
            ["he"] = "heb_Hebr",
            ["id"] = "ind_Latn",
            ["ms"] = "zsm_Latn",
            ["tl"] = "tgl_Latn",
            ["sw"] = "swh_Latn",
            ["cy"] = "cym_Latn",
            ["eu"] = "eus_Latn",
            ["gl"] = "glg_Latn",
            ["ca"] = "cat_Latn",
            ["af"] = "afr_Latn",
            ["is"] = "isl_Latn",
            ["mt"] = "mlt_Latn",
            ["sq"] = "als_Latn",
            ["mn"] = "khk_Cyrl",
            ["jv"] = "jav_Latn",
            ["su"] = "sun_Latn",
            ["mg"] = "plt_Latn",
            ["eo"] = "epo_Latn",

            // --- ISO 639-3 (GlotLID) ---
            ["eng"] = "eng_Latn",
            ["deu"] = "deu_Latn",
            ["fra"] = "fra_Latn",
            ["spa"] = "spa_Latn",
            ["ita"] = "ita_Latn",
            ["por"] = "por_Latn",
            ["nld"] = "nld_Latn",
            ["pol"] = "pol_Latn",
            ["ces"] = "ces_Latn",
            ["slk"] = "slk_Latn",
            ["slv"] = "slv_Latn",
            ["hun"] = "hun_Latn",
            ["ron"] = "ron_Latn",
            ["bul"] = "bul_Cyrl",
            ["hrv"] = "hrv_Latn",
            ["srp"] = "srp_Cyrl",
            ["rus"] = "rus_Cyrl",
            ["ukr"] = "ukr_Cyrl",
            ["bel"] = "bel_Cyrl",
            ["mkd"] = "mkd_Cyrl",
            ["bos"] = "bos_Latn",
            ["lit"] = "lit_Latn",
            ["lav"] = "lvs_Latn",
            ["est"] = "est_Latn",
            ["fin"] = "fin_Latn",
            ["swe"] = "swe_Latn",
            ["nob"] = "nob_Latn",
            ["nno"] = "nno_Latn",
            ["dan"] = "dan_Latn",
            ["tur"] = "tur_Latn",
            ["aze"] = "azj_Latn",
            ["kaz"] = "kaz_Cyrl",
            ["kir"] = "kir_Cyrl",
            ["uzb"] = "uzn_Latn",
            ["tgk"] = "tgk_Cyrl",
            ["ara"] = "arb_Arab",
            ["fas"] = "pes_Arab",
            ["urd"] = "urd_Arab",
            ["hin"] = "hin_Deva",
            ["ben"] = "ben_Beng",
            ["mar"] = "mar_Deva",
            ["tam"] = "tam_Taml",
            ["tel"] = "tel_Telu",
            ["mal"] = "mal_Mlym",
            ["kan"] = "kan_Knda",
            ["guj"] = "guj_Gujr",
            ["pan"] = "pan_Guru",
            ["nep"] = "npi_Deva",
            ["sin"] = "sin_Sinh",
            ["zho"] = "zho_Hans",
            ["cmn"] = "zho_Hans",
            ["yue"] = "yue_Hant",
            ["jpn"] = "jpn_Jpan",
            ["kor"] = "kor_Hang",
            ["vie"] = "vie_Latn",
            ["tha"] = "tha_Thai",
            ["khm"] = "khm_Khmr",
            ["lao"] = "lao_Laoo",
            ["mya"] = "mya_Mymr",
            ["kat"] = "kat_Geor",
            ["hye"] = "hye_Armn",
            ["heb"] = "heb_Hebr",
            ["ind"] = "ind_Latn",
            ["zsm"] = "zsm_Latn",
            ["msa"] = "zsm_Latn",
            ["tgl"] = "tgl_Latn",
            ["swa"] = "swh_Latn",
            ["cym"] = "cym_Latn",
            ["eus"] = "eus_Latn",
            ["glg"] = "glg_Latn",
            ["cat"] = "cat_Latn",
            ["afr"] = "afr_Latn",
            ["isl"] = "isl_Latn",
            ["mlt"] = "mlt_Latn",
            ["sqi"] = "als_Latn",
            ["khk"] = "khk_Cyrl",
            ["mon"] = "khk_Cyrl",
            ["jav"] = "jav_Latn",
            ["sun"] = "sun_Latn",
            ["mlg"] = "plt_Latn",
            ["epo"] = "epo_Latn",
            ["swh"] = "swh_Latn",
            ["lvs"] = "lvs_Latn",
            ["npi"] = "npi_Deva",
            ["ell"] = "ell_Grek",
            ["el"] = "ell_Grek",
            ["kor"] = "kor_Hang",
        };

    // FLORES-200 → ISO 639-1 (2-letter codes, e.g. "eng_Latn" → "en")
    private static readonly Lazy<Dictionary<string, string>> _flores200ToIso639_1 = new(() =>
        _isoToFlores200
            .Where(kv => kv.Key.Length == 2)
            .GroupBy(kv => kv.Value)
            .ToDictionary(g => g.Key, g => g.First().Key, StringComparer.OrdinalIgnoreCase));

    // FLORES-200 → ISO 639-3 (3-letter codes, e.g. "eng_Latn" → "eng")
    private static readonly Lazy<Dictionary<string, string>> _flores200ToIso639_3 = new(() =>
        _isoToFlores200
            .Where(kv => kv.Key.Length == 3)
            .GroupBy(kv => kv.Value)
            .ToDictionary(g => g.Key, g => g.First().Key, StringComparer.OrdinalIgnoreCase));
}
